export const environment = {
  baseApiUrl: '',
  clientId: '',
  client_secret: '',
  publicKey: '',
  authServiceUrl: '',
  userServiceUrl: '',
  homePath: '/main/home',
  home: '/me',
  logLevel: '5',
  tenantMgmtFacadeUrl: '',
  tenantmgmtServiceUrl: '',
  subscriptionServiceUrl: '',
  cognitoLogoutUrl: '',
};
