export const environment = {
  baseApiUrl: '',
  clientId: '',
  client_secret: '',
  publicKey: '',
  authServiceUrl: '',
  userServiceUrl: '',
  homePath: '',
  home: '',
  logLevel: '',
  tenantMgmtFacadeUrl: '',
  tenantmgmtServiceUrl: '',
  subscriptionServiceUrl: '',
  cognitoClientId: '',
  cognitoAuthClientDomain: '',
  logoutUri: '',
};
