export const environment = {
  production: true,
  clientId: '',
  publicKey: '',
  homePath: '/main/home',
  baseApiUrl: '',
  authServiceUrl: '',
  userServiceUrl: '',
  logLevel: 0,
  csp: {
    defaultSrc: [true],
    scriptSrc: [true],
    styleSrc: [true, "'unsafe-inline'"],
    imgSrc: [true],
    connectSrc: [true, 'env:baseApiUrl'],
    objectSrc: ['none'],
    baseUri: [true],
    formAction: [true],
    blockAllMixedContent: true,
  },
};
