export const environment = {
  production: true,
  clientId: '',
  publicKey: '',
  homePath: '/main/home',
  baseApiUrl: '',
  authServiceUrl: '',
  userServiceUrl: '',
  logLevel: 0,
  csp: {
    defaultSrc: ["'self'"],
    scriptSrc: ["'self'"],
    styleSrc: ["'self'", "'unsafe-inline'"],
    imgSrc: ["'self'"],
    connectSrc: ["'self'", 'env:baseApiUrl'],
    objectSrc: ['none'],
    baseUri: ["'self'"],
    formAction: ["'self'"],
    blockAllMixedContent: true,
  },
};
